# fly.toml app configuration file generated for finance-service-red-snow-9140 on 2025-04-16T15:32:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'finance-service-red-snow-9140'
primary_region = 'yul'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
